# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSMVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSMVM

  target 'iOSMVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSMVMUITests' do
    # Pods for testing
  end
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwifterSwift'
  pod 'Toaster'

end
